apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squid
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/acidonper/jump-app-gitops.git'
    path: .
    targetRevision: feature/jump-app-dev
    helm:
      valueFiles:
        - values-quay.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy: {}
