apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/acidonper/jump-app-gitops.git
  proxy: http://username:password@squid.squid.svc.cluster.local:3128
